<div class="wrapper style2">
	<article id="work">
		<header>
			<h2>Top Threads</h2>
		</header>
		<div class="container">
			<div class="row">
				<div class="4u 12u(mobile)">
					<section class="box style1">
						<span class="icon featured fa-bug"></span>
						<h3>#94513 - RDT crashes when registering</h3>
						<p>If you click on "Already have an account?" when on the RDT signup page, the program crashes.<br><a href="#" style="text-decoration:none">View more</a></p>
						
					</section>
				</div>
				<div class="4u 12u(mobile)">
					<section class="box style1">
						<span class="icon featured fa-bug"></span>
						<h3>#92316 - Patient comments button disappears randomly</h3>
						<p>The button to view patient comments vanishes after a random amount of time and can only be resolved by restarting the RDT.<br><a href="#" style="text-decoration:none">View more</a></p>
						
					</section>
				</div>
				<div class="4u 12u(mobile)">
					<section class="box style1">
						<span class="icon featured fa-bug"></span>
						<h3>#15436 - Authy 2FA is broken if you use Windows 8.1 or below</h3>
						<p>Downgrading from or not updating to Windows 10 results in 2FA being broken for no apparent reason, as 2FA worked before the Windows 10 release.<br><a href="#" style="text-decoration:none">View more</a></p>
						
					</section>
				</div>
			</div>
		</div>
		<footer>
			<a href="#portfolio" class="button big scrolly">View more</a>
		</footer>
	</article>
</div>

<!-- Portfolio -->
<div class="wrapper style3">
	<article id="portfolio">
		<header>
			<h2>Here’s some stuff I made recently.</h2>
			<p>Proin odio consequat sapien vestibulum consequat lorem dolore
				feugiat lorem ipsum dolore.</p>
		</header>
		<div class="container">
			<div class="row">
				<div class="4u 12u(mobile)">
					<article class="box style2">
						<a href="#" class="image featured"><img src="images/pic01.jpg"
							alt="" /></a>
						<h3>
							<a href="#">Magna feugiat</a>
						</h3>
						<p>Ornare nulla proin odio consequat.</p>
					</article>
				</div>
				<div class="4u 12u(mobile)">
					<article class="box style2">
						<a href="#" class="image featured"><img src="images/pic02.jpg"
							alt="" /></a>
						<h3>
							<a href="#">Veroeros primis</a>
						</h3>
						<p>Ornare nulla proin odio consequat.</p>
					</article>
				</div>
				<div class="4u 12u(mobile)">
					<article class="box style2">
						<a href="#" class="image featured"><img src="images/pic03.jpg"
							alt="" /></a>
						<h3>
							<a href="#">Lorem ipsum</a>
						</h3>
						<p>Ornare nulla proin odio consequat.</p>
					</article>
				</div>
			</div>
			<div class="row">
				<div class="4u 12u(mobile)">
					<article class="box style2">
						<a href="#" class="image featured"><img src="images/pic04.jpg"
							alt="" /></a>
						<h3>
							<a href="#">Tempus dolore</a>
						</h3>
						<p>Ornare nulla proin odio consequat.</p>
					</article>
				</div>
				<div class="4u 12u(mobile)">
					<article class="box style2">
						<a href="#" class="image featured"><img src="images/pic05.jpg"
							alt="" /></a>
						<h3>
							<a href="#">Feugiat aliquam</a>
						</h3>
						<p>Ornare nulla proin odio consequat.</p>
					</article>
				</div>
				<div class="4u 12u(mobile)">
					<article class="box style2">
						<a href="#" class="image featured"><img src="images/pic06.jpg"
							alt="" /></a>
						<h3>
							<a href="#">Sed amet ornare</a>
						</h3>
						<p>Ornare nulla proin odio consequat.</p>
					</article>
				</div>
			</div>
		</div>
		<footer>
			<p>Lorem ipsum dolor sit sapien vestibulum ipsum primis?</p>
			<a href="#contact" class="button big scrolly">Get in touch with me</a>
		</footer>
	</article>
</div>

<!-- Contact -->
<div class="wrapper style4">
	<article id="contact" class="container 75%">
		<header>
			<h2>Have me make stuff for you.</h2>
			<p>Ornare nulla proin odio consequat sapien vestibulum ipsum sed
				lorem.</p>
		</header>
		<div>
			<div class="row">
				<div class="12u">
					<form method="post" action="#">
						<div>
							<div class="row">
								<div class="6u 12u(mobile)">
									<input type="text" name="name" id="name" placeholder="Name" />
								</div>
								<div class="6u 12u(mobile)">
									<input type="text" name="email" id="email" placeholder="Email" />
								</div>
							</div>
							<div class="row">
								<div class="12u">
									<input type="text" name="subject" id="subject"
										placeholder="Subject" />
								</div>
							</div>
							<div class="row">
								<div class="12u">
									<textarea name="message" id="message" placeholder="Message"></textarea>
								</div>
							</div>
							<div class="row 200%">
								<div class="12u">
									<ul class="actions">
										<li><input type="submit" value="Send Message" /></li>
										<li><input type="reset" value="Clear Form" class="alt" /></li>
									</ul>
								</div>
							</div>
						</div>
					</form>
				</div>
			</div>
			<div class="row">
				<div class="12u">
					<hr />
					<h3>Find me on ...</h3>
					<ul class="social">
						<li><a href="#" class="icon fa-twitter"><span class="label">Twitter</span></a></li>
						<li><a href="#" class="icon fa-facebook"><span class="label">Facebook</span></a></li>
						<li><a href="#" class="icon fa-dribbble"><span class="label">Dribbble</span></a></li>
						<li><a href="#" class="icon fa-linkedin"><span class="label">LinkedIn</span></a></li>
						<li><a href="#" class="icon fa-tumblr"><span class="label">Tumblr</span></a></li>
						<li><a href="#" class="icon fa-google-plus"><span class="label">Google+</span></a></li>
						<li><a href="#" class="icon fa-github"><span class="label">Github</span></a></li>
						<!--
									<li><a href="#" class="icon fa-rss"><span>RSS</span></a></li>
									<li><a href="#" class="icon fa-instagram"><span>Instagram</span></a></li>
									<li><a href="#" class="icon fa-foursquare"><span>Foursquare</span></a></li>
									<li><a href="#" class="icon fa-skype"><span>Skype</span></a></li>
									<li><a href="#" class="icon fa-soundcloud"><span>Soundcloud</span></a></li>
									<li><a href="#" class="icon fa-youtube"><span>YouTube</span></a></li>
									<li><a href="#" class="icon fa-blogger"><span>Blogger</span></a></li>
									<li><a href="#" class="icon fa-flickr"><span>Flickr</span></a></li>
									<li><a href="#" class="icon fa-vimeo"><span>Vimeo</span></a></li>
									-->
					</ul>
					<hr />
				</div>
			</div>
		</div>
		<footer>
			<ul id="copyright">
				<li>&copy; Untitled. All rights reserved.</li>
				<li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
			</ul>
		</footer>
	</article>
</div>

<!-- Scripts -->
<script src="assets/js/jquery.min.js"></script>
<script src="assets/js/jquery.scrolly.min.js"></script>
<script src="assets/js/skel.min.js"></script>
<script src="assets/js/skel-viewport.min.js"></script>
<script src="assets/js/util.js"></script>
<!--[if lte IE 8]><script src="assets/js/ie/respond.min.js"></script><![endif]-->
<script src="assets/js/main.js"></script>

</body>
</html>