<!DOCTYPE html>
<?php
if($this->steel->config['development']['broadcastVersion']){
  echo '<!-- BugSpray '.$this->steel->config['version'].'-->';
}
?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title><?php echo $pageTitle; ?></title>

<?php
if($this->steel->config['advanced']['useCDN']){
  foreach ($this->steel->config['advanced']['CDN']['CSS'] as $name => $url){
    $sri = (isset($this->steel->config['advanced']['CDN']['CSS_SRI'][$name])) ? $this->steel->config['advanced']['CDN']['CSS_SRI'][$name] : false;

    $link = '<link rel="stylesheet" href="'.$url.'"';
    if($sri != false){ $link .= ' integrity="'.$sri.'" crossorigin="anonymous"'; }
    $link .= ' />';
    echo $link;
  }
}else{
  foreach ($this->steel->config['advanced']['localResources']['CSS'] as $url){
    $link = '<link rel="stylesheet" href="'.$url.'" />';
    echo $link;
  }
}
if($this->steel->config['general']['customCSS'] != false){
  $link = '<link rel="stylesheet" href="'.$this->steel->config['general']['customCSS'].'" />';
  echo $link;
}
foreach ($styles as $style){
  $link = '<link rel="stylesheet" href="'.$style.'" />';
  echo $link;
}
?>

</head>
<body style="padding-top: 50px">
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/"><?php echo $this->steel->config['general']['niceName']; ?></a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <?php
            //Static buttons have priority over dynamic [For definition, see settings.]
            foreach($this->steel->config['pages']['layout.phtml']['navbar-static']['left'] as $name => $url){
              $buttonDynamic = ($this->headerselect === $this->steel->config['pages']['layout.phtml']['navbar-static']['buttonHS'][$name]) ? " class='active'>" : ">";
              $button = '<li'.$buttonDynamic.'<a href="'.$url.'">'.$name.'</a></li>';
              echo $button;
            }
          ?>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <?php
            //Static buttons have priority over dynamic [For definition, see settings.]
            foreach($this->steel->config['pages']['layout.phtml']['navbar-static']['right'] as $name => $url){
              $buttonDynamic = ($this->headerselect === $this->steel->config['pages']['layout.phtml']['navbar-static']['buttonHS'][$name]) ? " class='active'>" : ">";
              $button = '<li'.$buttonDynamic.'<a href="'.$url.'">'.$name.'</a></li>';
              echo $button;
            }

            //Check to make sure security level is at two or below, allows for user-submitted
            //registrations.
            if(!$this->steel->config['security']['disableUserAuth']['disabled'] && $this->headerselect != 'HS::Login' && !$_SESSION['user']['session_active']){
              ?>
              <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><b><?php echo $this->steel->config['pages']['layout.phtml']['buttons']['login']; ?></b> <span class="caret"></span></a>
			<ul id="login-dp" class="dropdown-menu">
				<li>
					 <div class="row">
							<div class="col-md-12">
								 <form class="form" role="form" method="post" action=<?php echo '"'.$this->steel->config['general']['host'].'/login/process"';?> accept-charset="UTF-8" id="login-nav">
										<div class="form-group">
											 <label class="sr-only" for="inputEmail">E-Mail</label>
											 <input type="email" class="form-control" id="inputEmail" name="inputEmail" placeholder="E-Mail" required>
										</div>
										<div class="form-group">
											 <label class="sr-only" for="inputPassword">Password</label>
											 <input type="password" class="form-control" id="inputPassword" name="inputPassword" placeholder="Password" required>
                                             <div class="help-block text-right"><a href="">Forgot your password?</a></div>
										</div>
										<div class="form-group">
											 <button type="submit" class="btn btn-primary btn-block">Login</button>
										</div>
										<div class="checkbox">
											 <label>
											 <input type="checkbox" name="rememberMe"> keep me signed in
											 </label>
										</div>
								 </form>
							</div>
							<div class="bottom text-center">
								Need an account? <a href=<?php echo '"'.$this->steel->config['general']['host'].'/signup"';?>><b>Fill this form out.</b></a>
							</div>
					 </div>
				</li>

              <?php
            }else{
          ?>
          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><?php echo $_SESSION['user']['displayname']; ?><span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href=<?php echo '"'.$this->steel->config['general']['host'].'/logout"'; ?>>Sign Out</a></li>
            <li><a href="#">Report a bug</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
          <?php
        }
          ?>
        </ul>
      </div>
    </div>
  </nav>
  <?php
  include '../templates/'.$page;

  if($this->steel->config['advanced']['useCDN']){
    foreach ($this->steel->config['advanced']['CDN']['JS'] as $name => $url){
      $sri = (isset($this->steel->config['advanced']['CDN']['JS_SRI'][$name])) ? $this->steel->config['advanced']['CDN']['JS_SRI'][$name] : false;

      $script = '<script type="text/javascript" src="'.$url.'"';
      if($sri != false){ $script .= ' integrity="'.$sri.'" crossorigin="anonymous"'; }
      $script .= '></script>';
      echo $script;
    }
  }else{
    foreach ($this->steel->config['advanced']['localResources']['JS'] as $url){
      $script = '<script type="text/javascript" src="'.$url.'"></script>';
      echo $script;
    }
  }
  foreach ($scripts as $script){
    $link = '<script type="text/javascript" src="'.$script.'"></script>';
    echo $link;
  }

  ?>
</body>
