<div class="container-fluid">
    <section class="container">
		<div class="container-page">
      <?php
        if(isset($_SESSION['pages']['signup']['error'])){
      ?>
      <div clas="col-lg-12" style="padding-top: 10px">
        <div class="panel panel-danger">
          <div class="panel-heading">Registration Error <?php echo $_SESSION['pages']['signup']['error']; ?></div>
          <div class="panel-body">
            <?php
              echo $this->steel->application->messages->get_error($_SESSION['pages']['signup']['error']);
            ?>
          </div>
        </div>
      </div>
      <?php
        $cpd = (array_key_exists($_SESSION['pages']['signup']['error'], $this->steel->config['advanced']['errorMaps']) && $this->steel->config['advanced']['errorMaps'][$_SESSION['pages']['signup']['error']] == "CPD") ? true : null;
        if($cpd){
          $inputEmail = $_SESSION['pages']['signup']['error_fields']['inputEmail'];
          $inputDisplayname = $_SESSION['pages']['signup']['error_fields']['inputDisplayname'];
        }
        unset($_SESSION['pages']['signup']['error_fields']);
        unset($_SESSION['pages']['signup']['error']);
        }
      ?>
			<div class="col-md-6">
				<h3 class="dark-grey">Registration</h3>
        <?php
          echo '<form action="'.$this->steel->config['general']['host'].'/signup/process" method="post" id="regForm">';
        ?>
        <div class="form-group col-lg-12">
          <div class="input-group">
            <?php
              if(!isset($cpd)){
                echo $this->steel->application->create_input_field('fa fa-envelope', 'email', 'E-Mail', 'inputEmail');
              }else{
                echo $this->steel->application->create_input_field_with_value('fa fa-envelope', 'email', 'E-Mail', $inputEmail, 'inputEmail');
              }
            ?>
          </div>
        </div>

        <div class="form-group col-lg-12">
          <div class="input-group">
            <?php
              if(!isset($cpd)){
                echo $this->steel->application->create_input_field('fa fa-user', 'text', 'Display Name', 'inputDisplayname');
              }else{
                echo $this->steel->application->create_input_field_with_value('fa fa-user', 'text', 'Display Name', $inputDisplayname, 'inputDisplayname');
              }
            ?>
          </div>
        </div>

				<div class="form-group col-lg-6">
          <div class="input-group">
            <?php
              echo $this->steel->application->create_input_field('fa fa-unlock-alt', 'password', 'Password', 'inputPassword');
            ?>
          </div>
				</div>

				<div class="form-group col-lg-6">
          <div class="input-group">
            <?php
              echo $this->steel->application->create_input_field('fa fa-unlock-alt', 'password', 'Confirm Password', 'inputPasswordConfirm');
            ?>
          </div>
				</div>

				<div class="col-sm-6 pull-right">
					<input type="checkbox" class="checkbox" />Send notifications to this email
				</div>
      </form>

			</div>

			<div class="col-md-6">
                            <h3 class="dark-grey">
                                  Terms and Conditions
                            </h3><p>
                                    By clicking on "Register" you agree to BugSpray's Terms and Conditions
                                  </p>
                                  <p>
                                    BugSpray and its data is proprietary. Making a request for your data does not have to be filled.
                                  </p>
                                  <p>
                                    Users are expected to be polite and listen to other users along with their complaints. The violation of this rule means you are subject to a suspension or termination, with no exceptions or explanations needed (although you may receive an e-mail explaining why.)
                                  </p>
                                  <p>
                                    Circumvention of bans from BugSpray may result in the blacklisting of your IP altogether, or resulting in registrations requiring moderator approval.
                                  </p>
                                  <p>
                                    BugSpray's terms may be updated without notice; it is your responsibility to check these terms regularly for changes. Failure to check the terms on your part does not result in an exemption of user discipline.
                                  </p>
				<button type="submit" class="btn btn-primary" form="regForm">Register</button>
			</div>
		</div>
	</section>
</div>
